### ISSUE TITLE
Doubt about the filters of transposed convolution?

### ISSUE THREAD

**Issue by EpsAvlc** [RobustFieldAutonomyLab/lidar_super_resolution#2]
I read your paper and in this paper, the first two transposed convolution is drawn as:
![image](https://user-images.githubusercontent.com/20700856/80485393-e396ed00-898b-11ea-89d2-1370bd0c8e29.png)
It seems that the output of first two transposed convolutions are a 1x32x1024 tensor and a 1x64x1024 tensor. However in your code the transposed convolutions are:
```python
   filters = 64
    for _ in range(int(np.log(upscaling_factor) / np.log(2))):
        x0 = up_block(x0, filters, strides=(2,1)
```
Which make the output of transposed convolutions are a 64x32x1024 tensor and a 64x64x1024 tensor.
Which is right?
(I am not familiar with tensorflow, and maybe i misunderstood the code).

**Comment by TixiaoShan** [comment]
@EpsAvlc 
The code seems correct to me. A stride of (2,1) will upscale the row number of the image.

**Comment by EpsAvlc** [comment]
@TixiaoShan May be I didn't explain my doubt well.
![80485393-e396ed00-898b-11ea-89d2-1370bd0c8e29](https://user-images.githubusercontent.com/20700856/80549770-aca6f280-89f0-11ea-840a-219e4c33faa5.png)
Whether the filter bank of the first two transposed convolution layers is 1 or 64?
In the picture, it seems 1. In the code, it seems 64.

**Comment by TixiaoShan** [comment]
@EpsAvlc 
Ah, it's all 1, not 64.

**Comment by EpsAvlc** [comment]
Got it. Thank you.
